### ISSUE TITLE
Change scaling of Figures 4 and S2

### ISSUE THREAD

**Issue by zkamvar** [everhartlab/sclerotinia-366#16]
[Figure 4](https://github.com/everhartlab/sclerotinia-366/blob/v1.0/results/figures/publication/mlg-11.pdf) and [Figure S2](https://github.com/everhartlab/sclerotinia-366/blob/v1.0/results/figures/publication/mlg-16.pdf) in the paper currently have the nodes scaled by radius, not area 🤦‍♂️

Luckily, the numbers are presented on the figure, so **the interpretation does not change** even if I rescale the nodes by area. 

For reference, figure 4 would look like this rescaled (I also modified the legend because the sizes there changed as well:

![image](https://user-images.githubusercontent.com/3639446/32333303-8d014672-bfb5-11e7-88ba-9027a160a88d.png)

Figure S2 would look like this:

![image](https://user-images.githubusercontent.com/3639446/32333328-9c5c6ffc-bfb5-11e7-9454-e2291fef0374.png)

@sporangia what do you think? Should we contact PeerJ about this?

**Comment by sporangia** [comment]
Let's just make the change and notify the editor in our response to reviews.
